use_frameworks!

platform :ios, '9.0'

target 'PreventLookingManager_Example' do
  pod 'PreventLookingManager', :path => '../'

  target 'PreventLookingManager_Tests' do
    inherit! :search_paths

    
  end
end
